name: Build and Publish Python Package

on:
  push:
    tags:
      - '*'

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: Install poetry
      run: pip install poetry
    - name: Build Wheel
      run: poetry build -f wheel
    - name: Upload Wheel
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/*

    # Publishing to PyPI. Necessary?
    # - name: Publish to PyPI
    #   uses: pypa/gh-action-pypi-publish@master
    #   with:
    #     user: __token__
    #     password: ${{ secrets.PYPI_API_TOKEN }}
