name: Build and Publish Python Package

on:
  push:
    tags:
      - '*'

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: Install poetry
      run: pip install poetry
    - name: Build Wheel
      run: poetry build -f wheel
    - name: Upload Wheel
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/*
    - name: Check Version Format in Tag
      if: startsWith(github.ref, 'refs/tags/v')
      uses: nowsprinting/check-version-format-action@v4.0.2
      id: check-version
      with:
        prefix: 'v'
    - name: Publish to PyPI
      if: startsWith(github.ref, 'refs/tags/')
      env:
        TWINE_USERNAME: '__token__'
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        pip install twine
        twine upload dist/*
