name: Python Tests

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  issues: write
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Run pytest with coverage and generate report
        run: poetry run pytest --cov=tests --cov-report=xml tests/
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml
